spring.application.name=skawallet

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/skawallet_db}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.port=${PORT:8080}
jwt.expiration=3600000
